name: SonarQube Analysis
on:
 push:
   branches:
     - main
   paths:
     - 'src/**'
     - 'pom.xml'
     - 'test/**'
 pull_request:
   paths:
     - 'src/**'
     - 'pom.xml'
     - 'test/**'

jobs:
 sonar:
   runs-on: ubuntu-latest
   steps:
     - name: Check out the repository
       uses: actions/checkout@v4
       
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: '17'
         
     - name: Cache Maven packages
       uses: actions/cache@v4
       with:
         path: ~/.m2
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
           ${{ runner.os }}-maven
           
     - name: Build and Run SonarQube Analysis
       run: >
         mvn clean verify sonar:sonar 
         -Dsonar.projectKey=${{ secrets.PROJECT_KEY }} 
         -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} 
         -Dsonar.login=${{ secrets.SONAR_TOKEN }}
       
     - name: Upload SonarQube Report
       if: failure()
       uses: actions/upload-artifact@v4
       with:
         name: sonar-report
         path: target/sonar/report-task.txt
